openapi: 3.0.3

info:
  title: Smart Meeting Assistant API
  version: "1.0.0"
  description: >
    API del Smart Meeting Assistant (SMA). Permite registrar usuarios, proponer
    reuniones, administrar participantes, almacenar resúmenes y generar tareas
    de seguimiento.
  contact:
    name: |
      Equipo 42
      Miguel Silva Ramos - A01328387
      José Montante - A01150895
      Hector Jorge Morales Arch - A01796487
      Carlos Del Castillo Rey - A01796595

servers:
  - url: https://firestore.googleapis.com/v1/projects/smart-meeting-assistant-1a3c8/databases/(default)/documents/
    description: Entorno principal (simulado)

tags:
  - name: Usuarios
    description: Operaciones relacionadas con usuarios registrados
  - name: Reuniones
    description: Gestión de reuniones y tareas
  - name: Disponibilidad
    description: Sugerencias de horarios comunes
  - name: Sistema
    description: Estado del servicio

externalDocs:
  description: Documentación técnica del proyecto
  url: https://github.com/equipo42/sma-docs

security:
  - ApiKeyAuth: []
  - BearerAuth: []
