openapi: 3.0.3

info:
  title: Smart Meeting Assistant API
  version: "1.0.0"
  description: >
    API del Smart Meeting Assistant (SMA). Permite registrar usuarios, proponer
    reuniones, administrar participantes, almacenar resúmenes y generar tareas
    de seguimiento.
  contact:
    name: |
      Equipo 42
      Miguel Silva Ramos - A01328387
      José Montante - A01150895
      Hector Jorge Morales Arch - A01796487
      Carlos Del Castillo Rey - A01796595
    

servers:
  - url: https://firestore.googleapis.com/v1/projects/smart-meeting-assistant-1a3c8/databases/(default)/documents/
    description: Entorno principal (simulado)

paths:

  /users:
    get:
      summary: Listar usuarios conocidos
      description: Devuelve todos los usuarios registrados en el SMA.
      parameters:
        - in: query
          name: email
          schema:
            type: string
          description: Filtrar por email exacto.
      responses:
        "200":
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "400":
          description: Parámetros inválidos
    post:
      summary: Crear usuario
      description: Registra un nuevo usuario/participante en el sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Datos incompletos o inválidos

  /users/{userId}:
    get:
      summary: Obtener detalle de usuario
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID interno del usuario en SMA.
      responses:
        "200":
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Usuario no encontrado
    patch:
      summary: Actualizar usuario
      description: Actualiza datos como zona horaria o correo alterno.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Usuario actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Datos inválidos
        "404":
          description: Usuario no encontrado

  /meetings:
    get:
      summary: Listar reuniones
      description: Lista reuniones filtrando por rango de tiempo o por organizador.
      parameters:
        - in: query
          name: from
          required: false
          schema:
            type: string
            format: date-time
          description: Incluir reuniones que inician a partir de esta marca de tiempo (ISO8601).
        - in: query
          name: to
          required: false
          schema:
            type: string
            format: date-time
          description: Incluir reuniones que terminan antes de esta marca de tiempo (ISO8601).
        - in: query
          name: organizerId
          required: false
          schema:
            type: string
          description: Filtrar por el ID del organizador.
      responses:
        "200":
          description: Lista de reuniones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meeting"
        "400":
          description: Parámetros inválidos
    post:
      summary: Crear reunión
      description: Crea una reunión propuesta por el asistente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Meeting"
      responses:
        "201":
          description: Reunión creada (tentative/scheduled)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meeting"
        "400":
          description: Datos inválidos

  /meetings/{meetingId}:
    get:
      summary: Obtener detalles de una reunión
      parameters:
        - in: path
          name: meetingId
          required: true
          schema:
            type: string
          description: ID interno de la reunión.
      responses:
        "200":
          description: Reunión encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meeting"
        "404":
          description: Reunión no encontrada
    patch:
      summary: Actualizar reunión
      description: Reprogramar la hora, actualizar el título, etc.
      parameters:
        - in: path
          name: meetingId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Meeting"
      responses:
        "200":
          description: Reunión actualizada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meeting"
        "400":
          description: Datos inválidos
        "404":
          description: Reunión no encontrada
    delete:
      summary: Cancelar reunión
      parameters:
        - in: path
          name: meetingId
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Reunión cancelada/eliminada
        "404":
          description: Reunión no encontrada

  /meetings/{meetingId}/summary:
    post:
      summary: Guardar resumen de la reunión
      description: Sube/actualiza el resumen (notas, acuerdos, decisiones tomadas).
      parameters:
        - in: path
          name: meetingId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                summaryText:
                  type: string
                  description: Resumen generado por el asistente o por el usuario.
              required:
                - summaryText
      responses:
        "200":
          description: Resumen guardado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meeting"
        "404":
          description: Reunión no encontrada

  /meetings/{meetingId}/action-items:
    get:
      summary: Listar action items de una reunión
      parameters:
        - in: path
          name: meetingId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lista de action items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "404":
          description: Reunión no encontrada
    post:
      summary: Crear action item en una reunión
      description: Crea una tarea de seguimiento asignable a un participante.
      parameters:
        - in: path
          name: meetingId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Action item creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Datos inválidos
        "404":
          description: Reunión no encontrada

  /availability/suggest:
    post:
      summary: Proponer horarios disponibles
      description: Calcula bloques de tiempo recomendados en común entre varias personas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AvailabilityRequest"
      responses:
        "200":
          description: Slots sugeridos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AvailabilitySuggestion"
        "400":
          description: Datos inválidos (por ejemplo, sin participantes)

components:
  schemas:

    User:
      type: object
      description: Representa a un participante/usuario conocido por el SMA.
      properties:
        id:
          type: string
          format: uuid
          description: Identificador interno del usuario.
        displayName:
          type: string
          description: Nombre legible (por ejemplo, "Karla López").
        email:
          type: string
          format: email
        timezone:
          type: string
          description: Zona horaria IANA, ej. "America/Los_Angeles".
        role:
          type: string
          description: Rol del usuario respecto a una reunión (Organizer, RequiredAttendee, OptionalAttendee).
      required:
        - id
        - displayName
        - email

    Meeting:
      type: object
      description: Reunión gestionada/creada por el Smart Meeting Assistant.
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          description: Título o propósito breve de la reunión.
        startTime:
          type: string
          format: date-time
          description: Hora de inicio propuesta/confirmada.
        endTime:
          type: string
          format: date-time
        status:
          type: string
          enum: [tentative, scheduled, cancelled]
          description: Estado actual de la reunión.
        location:
          type: string
          description: Ubicación física o virtual (Teams, Zoom, Sala 2-B).
        participants:
          type: array
          description: Lista de asistentes.
          items:
            $ref: "#/components/schemas/User"
        agenda:
          type: array
          description: Temas planeados.
          items:
            type: string
        summary:
          type: string
          description: Resumen/acta de acuerdos.
        Tasks:
          type: array
          description: Tareas derivadas de la reunión.
          items:
            $ref: "#/components/schemas/Task"
      required:
        - id
        - title
        - startTime
        - endTime
        - participants

    Task:
      type: object
      description: Tarea derivada de una reunión.
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
          description: Acción a realizar.
        ownerUserId:
          type: string
          description: ID del usuario responsable.
        dueDate:
          type: string
          format: date
          description: Fecha límite propuesta.
        status:
          type: string
          enum: [open, done]
      required:
        - id
        - description
        - ownerUserId
        - status

    AvailabilityRequest:
      type: object
      description: Parámetros para buscar horarios comunes.
      properties:
        participantIds:
          type: array
          items:
            type: string
          description: IDs de usuarios que deben estar disponibles.
        durationMinutes:
          type: integer
          example: 30
          description: Duración deseada del bloque.
        earliestStart:
          type: string
          format: date-time
          description: No proponer horarios antes de esta fecha/hora.
        latestEnd:
          type: string
          format: date-time
          description: No proponer horarios después de esta fecha/hora.
      required:
        - participantIds
        - durationMinutes
        - earliestStart
        - latestEnd

    AvailabilitySuggestion:
      type: object
      description: Slot recomendado por el motor de disponibilidad.
      properties:
        slotStart:
          type: string
          format: date-time
        slotEnd:
          type: string
          format: date-time
        score:
          type: number
          format: float
          description: Qué tan bueno es el slot (1.0 = ideal).
      required:
        - slotStart
        - slotEnd
        - score
